"""Some predefined components.

All the components are "saved" as classes in limbus.components, being the original module name used
to create a clear name for the component.
E.g.:
limbus.components.base.ImageReader -> limbus.components.limbus___ImageReader
torch.unbind                       -> limbus.components.torch___unbind
kornia.color.rgb_to_hls            -> limbus.components.kornia___color___rgb_to_hls

The components automatically created are always saved in the limbus.components module using ___ to
denote the original module.
"""
from typing import Any, List
from pathlib import Path
import logging

import numpy as np
import PIL
import torch
import visdom
import kornia

from limbus.core import Component, ComponentState, Params


log = logging.getLogger(__name__)


class ImageReader(Component):
    """Component that holds a constant.

    Args:
        name: component name.
        value: path to an image or image folder.

    """
    def __init__(self, name: str, path: Path, batch_size: int = 1):
        super().__init__(name)
        self._value: List[Path] = []
        self._batch_size = batch_size
        self._idx = 0
        if Path(path).is_dir():
            self._value = sorted(list(Path(path).glob("*")))
        else:
            self._value.append(Path(path))

    @staticmethod
    def register_outputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("image", torch.Tensor)
        return outputs

    def forward(self) -> ComponentState:  # noqa: D102
        images: List[torch.Tensor] = []
        batch_size = 0
        while batch_size < self._batch_size:
            if self._idx >= len(self._value):
                return ComponentState.STOPPED
            try:
                self._idx += 1
                images.append(
                    kornia.image_to_tensor(np.asarray(PIL.Image.open(str(self._value[self._idx]))))
                )
                batch_size += 1
            except:
                # avoid crashing the whole pipeline when there is a corrupted image or non-image file
                pass
        batch = torch.stack(images)
        # images must be in the range [0, 1]
        batch = batch.div(255.).clamp(0, 1)
        self._outputs.set_param("image", batch)
        return ComponentState.OK


class ImageShow(Component):
    """Component to show the input image."""
    def __init__(self, name: str, window: str = ""):
        super().__init__(name)
        self._window = window
        if window == "":
            self._window = self._name
        self._enabled = True
        try:
            self._visdom = visdom.Visdom(port=8087, raise_exceptions=True)
        except:
            self._enabled = False

        if not self._enabled:
            log.warning("ImageShow is disabled!!!")
            return

        if not self._visdom.check_connection():
            raise ConnectionError('Error connecting with the visdom server.')

    @staticmethod
    def register_inputs() -> Params:  # noqa: D102
        inputs = Params()
        inputs.declare("image", torch.Tensor)
        return inputs

    def forward(self) -> ComponentState:  # noqa: D102
        opts = {'title': self._window}
        # TODO: for batches use `images`
        images = self._inputs.get_param("image")
        if self._enabled:
            if images.shape[0] == 1:
                self._visdom.image(images[0], win=self._window, opts=opts)
            else:
                self._visdom.images(images, nrow=int(images.shape[0]), win=self._window, opts=opts)
            return ComponentState.OK
        # TODO: find a way to notify when the component is DISABLED or retruns an ERROR
        return ComponentState.DISABLED

    def finish_iter(self) -> None:  # noqa: D102
        pass


class Constant(Component):
    """Component that holds a constant."""
    def __init__(self, name: str, value: Any):
        super().__init__(name)
        self._value = value

    @staticmethod
    def register_outputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("out", Any, arg="value")
        return outputs

    def forward(self) -> ComponentState:  # noqa: D102
        # TODO: next line could be autogenerated fron the declare() method since there we are already linking both.
        self._outputs.set_param("out", self._value)
        return ComponentState.OK


class Printer(Component):
    """Component to print the input in the console."""
    def __init__(self, name: str):
        super().__init__(name)

    @staticmethod
    def register_inputs() -> Params:  # noqa: D102
        inputs = Params()
        inputs.declare("inp", Any)
        return inputs

    def forward(self) -> ComponentState:  # noqa: D102
        print(self._inputs.get_param("inp"))
        return ComponentState.OK


# Example of a simple component created from the API
class Adder(Component):
    """Component to add two inputs and output the result."""
    def __init__(self, name: str):
        super().__init__(name)

    @staticmethod
    def register_inputs() -> Params:  # noqa: D102
        inputs = Params()
        inputs.declare("a", torch.Tensor)
        inputs.declare("b", torch.Tensor)
        return inputs

    @staticmethod
    def register_outputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("out", torch.Tensor)
        return outputs

    def forward(self) -> ComponentState:  # noqa: D102
        a = self._inputs.get_param("a")
        b = self._inputs.get_param("b")
        self._outputs.set_param("out", a + b)
        return ComponentState.OK


# temporal classes while we solve pending issues. TODO: allow components as parameters
class ImageStitcher(Component):
    """Component to stitch images together."""
    def __init__(self, name: str, estimator: str = 'ransac', blending_method: str = 'naive'):
        super().__init__(name)
        gftt_hardnet_matcher = kornia.feature.LocalFeatureMatcher(kornia.feature.GFTTAffNetHardNet(500),
                                                                  kornia.feature.DescriptorMatcher('snn', 0.8))
        self._is = kornia.contrib.ImageStitcher(gftt_hardnet_matcher, estimator, blending_method)

    @staticmethod
    def register_inputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("imgs", torch.Tensor)
        return outputs

    @staticmethod
    def register_outputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("out", torch.Tensor)
        return outputs

    def forward(self) -> ComponentState:  # noqa: D102
        self._outputs.set_param("out", self._is(*(self._inputs.get_param("imgs").unsqueeze(1))))
        return ComponentState.OK


class ImageRegistrator(Component):
    """Component to register images."""
    def __init__(self, name: str):
        super().__init__(name)
        self._ir = kornia.geometry.ImageRegistrator()

    @staticmethod
    def register_inputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("img_src", torch.Tensor)
        outputs.declare("img_dst", torch.Tensor)
        return outputs

    @staticmethod
    def register_outputs() -> Params:  # noqa: D102
        outputs = Params()
        outputs.declare("homo", torch.Tensor)
        return outputs

    def forward(self) -> ComponentState:  # noqa: D102
        self._outputs.set_param("homo",
                                self._ir.register(
                                    self._inputs.get_param("img_src"),
                                    self._inputs.get_param("img_dst")))
        return ComponentState.OK
